name: CI for changes

on:
  workflow_call:
    outputs:
      app:
        description: "If changes in the files"
        value: ${{ jobs.changes.outputs.app }}

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
    #  frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          app:
            - 'app/**'
            - 'alembic/**'
            - 'tests/**'
            - 'pyproject.toml'
            - 'poetry.lock'
            - 'uv.lock'
            - 'setup.cfg'
            - 'Dockerfile'
            - 'docker-compose.test.yaml'

