name: CI for changes

on:
  workflow_call:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app: ${{ steps.filter.outputs.app }}
    #  frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          app:
            - 'app/**'
            - 'alembic/**'
            - 'tests/**'
            - 'pyproject.toml'
            - 'poetry.lock'
            - 'setup.cfg'
            - 'Dockerfile'
            - 'docker-compose.test.yaml'
    
  test:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.app == 'true' }}
    steps:
      - name: test
        run: echo "app = ${{needs.changes.outputs.app}}"
